name: Build EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies with pipwin for PyAudio
        run: |
          python -m pip install --upgrade pip
          pip install pipwin
          pipwin install pyaudio
          pip install -r requirements.txt

      - name: Run the app to make sure it works
        run: |
          python main.py
        continue-on-error: true

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build .exe with PyInstaller using .spec
        run: pyinstaller main.spec

      - name: Upload built EXE
        uses: actions/upload-artifact@v4
        with:
          name: Navigaze-exe
          path: dist/main.exe
